language: node_js
node_js:
  - 4.2
  - 4.0
  - 0.12
  - iojs
os:
  - linux
install:
  - npm install
  - gem install sass
cache:
  directories:
  - node_modules
script: make
after_success:
  - make release
  - bash ./deploy.sh
env:
  global:
  - secure: 38b4teCLWUJk5ahleudhMwszwYuZPDH8ysC4TSl27gNeap4VnPes9y0PWNou6yegzq/uVLgmxe7eapQcEZaZKZYCAPW/+0LylbV9iulaTIhwcd9B3zgLxl3kiL7lnmpkUr8dkrqyzF/EcwrqeWmBKPlWCpkngS0CROXdEJBSVTvLk2spmde84HEagJ0tveaUX1rNh8yJzHIqcTI+2G0QQQhV+t+2G57PxF6QX+rjdPoZ2+kEUd5HqYKCbztPTLTm8GZqAjo5M8jykbdAoES6cdmF382ZnNRX0maaSEBZPhcKWKAsf+8RyNo93iQhp2xEc3TwZjk8Kzr6QIJQjxY+UNzY/skfPhnLZ1mnb7EbWdIzpESeacPYuIpmWjiUTYQPAckZJVPos+htEvm2y8W3kBdMzpM1snP0NGoj2GL5WzB8/sdIci+h0PVVEbr0xzejMML6Waew7UuiB56tzgt+ZKGQXwiUNjTw67wNhKiqBWI0BC4/NcmQg27KKZZwqrfoYR1aSCoG6yxC7O62ZboC9Hb4fc9dKdeG952Y/2QQglsO0qIQD8b3AO9N1RQsUpv18EgpXQKV+o/3gPir0x1uVvF7Oc+bPaPaegIdPoFtAUlfl6dqxHYUVGKJEi6M+RTsWHk/x2SMBy7WPZmGPEH+H6cl0sd+bNH0If8DvJ20qK8=